gsb_profil_homepage:
    path:     /profil
    defaults: { _controller: GsbFraisProfilBundle:GestionProfil:index }

gsb_profil_saisie_frais:
    path:     /saisieFrais
    defaults: { _controller: GsbFraisProfilBundle:SaisirFrais:saisir}

gsb_profil_afficher_mois:
    path:     /fraisDuMois
    defaults: { _controller: GsbFraisProfilBundle:FraisDuMois:afficher}