gsb_profil_homepage:
    path:     /profil
    defaults: { _controller: GsbFraisProfilBundle:GestionProfil:index }

gsb_profil_saisie_frais:
    path:     /saisieFrais
    defaults: { _controller: GsbFraisProfilBundle:SaisirFrais:saisir}

gsb_profil_afficher_mois:
    path:     /fraisDuMois
    defaults: { _controller: GsbFraisProfilBundle:FraisDuMois:afficher}

gsb_profil_historique:
    path:     /historique
    defaults: { _controller: GsbFraisProfilBundle:Historique:selectionner}

gsb_profil_historique_selection:
    path:     /historiqueSelection/{date}
    defaults: { _controller: GsbFraisProfilBundle:Historique:visu}